### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [oxen-io/oxen-mobile-wallet#11]
Ref: https://gitlab.com/fdroid/rfp/-/issues/1787

This recipe:
```
Builds:
  - versionName: 1.0.6
    versionCode: 6
    commit: v1.0.6
    subdir: android/app
    gradle:
      - yes
    output: build/app/outputs/apk/release/app-release.apk
    srclibs:
      - flutter@2.2.3
    prebuild:
      - echo "flutter.sdk=$$flutter$$" >> ../local.properties
      - $ANDROID_HOME/tools/bin/sdkmanager 'cmake;3.10.2.4988404'
    build:
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter packages pub get
      - $$flutter$$/bin/flutter build apk
```
yields this error: https://gitlab.com/-/snippets/2145070

> To download the latest build of the Oxen Dependencies run
./tool/download-android-deps.sh https://oxen.rocks/oxen-io/oxen-core/oxen-stable-android-deps-LATEST.tar.xz
Or build the Oxen Dependencies and copy the Android deps into oxen_coin/ios/External/android/oxen

Those can be build from https://github.com/oxen-io/oxen-core ?
